### ISSUE TITLE
Contract::Validate() is broken

### ISSUE THREAD

**Issue by n-rodriguez** [trailblazer/trailblazer-macro-contract#16]
Hi there!

`Contract::Validate()` is broken since last upgrade to `trailblazer-activity (0.8.2)`.

Here my operation : 

```ruby
# frozen_string_literal: true

module Admin::Countries::Operation
  class Create < Trailblazer::Operation
    step Model(Country, :new)
    step Contract::Build(constant: Admin::Countries::Contract::Create)
    step Contract::Validate(key: :country)
    step Contract::Persist()
  end
end
```

The error :

```console
nicolas@tchoum-laptop:~/PROJECTS/CONCERTO/concerto$ bin/rspec spec/concepts/admin/countries/operation/create_spec.rb 
Running via Spring preloader in process 7219

An error occurred while loading ./spec/concepts/admin/countries/operation/create_spec.rb.
Failure/Error: step Contract::Validate(key: :country)

TypeError:
  wrong argument type Class (expected Module)
# ./app/concepts/admin/countries/operation/create.rb:7:in `<class:Create>'
# ./app/concepts/admin/countries/operation/create.rb:4:in `<module:Operation>'
# ./app/concepts/admin/countries/operation/create.rb:3:in `<top (required)>'
# ./spec/concepts/admin/countries/operation/create_spec.rb:3:in `<main>'
# -e:1:in `<main>'
No examples found.
```
If I comment `Contract::Validate` it "works" : 

```console
nicolas@tchoum-laptop:~/PROJECTS/CONCERTO/concerto$ bin/rspec spec/concepts/admin/countries/operation/create_spec.rb 
Running via Spring preloader in process 7379

Randomized with seed 32177
[rspec-sidekiq] WARNING! Sidekiq will *NOT* process jobs in this environment. See https://github.com/philostler/rspec-sidekiq/wiki/FAQ-&-Troubleshooting
.FF

Failures:

  1) Admin::Countries::Operation::Create invalid creation when name is already taken should not be persisted
     Failure/Error:
       expect(result['contract.default'].errors.messages).to eq({
         name: ["n'est pas disponible"],
       })
     
       expected: {:name=>["n'est pas disponible"]}
            got: {:name=>["doit être rempli(e)"]}
     
       (compared using ==)
     
       Diff:
       @@ -1,2 +1,2 @@
       -:name => ["n'est pas disponible"],
       +:name => ["doit être rempli(e)"],
       
     # ./spec/concepts/admin/countries/operation/create_spec.rb:35:in `block (4 levels) in <main>'
     # -e:1:in `<main>'

  2) Admin::Countries::Operation::Create valid creation with valid params should be persisted
     Failure/Error: expect(result.success?).to be true
     
       expected true
            got false
     # ./spec/concepts/admin/countries/operation/create_spec.rb:12:in `block (4 levels) in <main>'
     # -e:1:in `<main>'

Finished in 0.93337 seconds (files took 0.25741 seconds to load)
3 examples, 2 failures
```

The spec :

```ruby
require 'rails_helper'

describe Admin::Countries::Operation::Create do

  let(:params)  { { country: attributes_for(:country) } }
  let(:context) { {} }
  let(:result)  { described_class.({ params: params }.merge(context)) }

  describe 'valid creation' do
    context 'with valid params' do
      it 'should be persisted' do
        expect(result.success?).to be true
        expect(result[:model].persisted?).to be true
      end
    end
  end

  describe 'invalid creation' do
    context 'when name is empty' do
      let(:params) { { country: attributes_for(:country, name: '') } }

      it 'should not be persisted' do
        expect(result['contract.default'].errors.messages).to eq({
          name: ["doit être rempli(e)"],
        })
      end
    end

    context 'when name is already taken' do
      let(:params) { { country: attributes_for(:country, name: 'Foo') } }

      it 'should not be persisted' do
        described_class.(params: params)

        expect(result['contract.default'].errors.messages).to eq({
          name: ["n'est pas disponible"],
        })
      end
    end
  end
end
```

**Comment by emaglio** [comment]
Weird, have you updated also `trailblazer-operation` and `trailblazer-macro/macro-contract`?
Using that gem version in my client project and I'm not getting that error.
https://github.com/trailblazer/trailblazer-activity/wiki/Migration-2.1.rc1-to-2.1.rc11

**Comment by n-rodriguez** [comment]
> Weird, have you updated also `trailblazer-operation` and `trailblazer-macro/macro-contract`?

Yes. In `gems.rb` I only have `gem 'trailblazer-rails'`.

From 'gems.locked` : 

```
    trailblazer (2.1.0.rc1)
      declarative
      trailblazer-macro (>= 2.1.0.rc1, < 2.2.0)
      trailblazer-macro-contract (= 2.1.0.rc1)
      trailblazer-operation
    trailblazer-activity (0.8.2)
      trailblazer-context
    trailblazer-activity-dsl-linear (0.1.5)
      trailblazer-activity
    trailblazer-context (0.1.2)
    trailblazer-loader (0.1.2)
    trailblazer-macro (2.1.0.rc11)
      trailblazer-activity-dsl-linear (>= 0.1.5, < 0.2.0)
      trailblazer-operation (>= 0.5.0)
    trailblazer-macro-contract (2.1.0.rc1)
      reform (>= 2.2.0, < 3.0.0)
    trailblazer-operation (0.5.1)
      trailblazer-activity-dsl-linear (>= 0.1.5, < 1.0.0)
      trailblazer-context (>= 0.1.1, < 0.3.0)
    trailblazer-rails (2.1.7)
      railties (>= 4.0.0)
      trailblazer (>= 2.1.0.beta1, < 2.2.0)
      trailblazer-loader (>= 0.1.0)
```

**Comment by seuros** [comment]
You need to either downgrade trailblazer-macro to `2.1.0.rc1` or use master for trailblazer gem.

There are some syntax changes in rc11

**Comment by n-rodriguez** [comment]
> use master for trailblazer gem.

It works! Thank you :+1:
